SCHEMA = [
    'date',
    'employee_title',
    'City',
    'Country',
    'employee_status',
    'review_title',
    'helpful',
    'pros',
    'cons',
    'advice_to_mgmt',
    'rating_overall',
    # 'rating_balance',
    # 'rating_culture',
    # 'rating_career',
    # 'rating_comp',
    # 'rating_mgmt',
    'recommends',
    'positive_outlook',
    'approves_of_CEO',
    'responsed_by',
    'responder_designation',
    'response'
]