apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\adityg1\Desktop\aditya\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-server
  name: redis-server
  namespace: aditya
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: redis-server
status:
  loadBalancer: {}
