apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\adityg1\Desktop\aditya\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-server
  name: redis-server
  namespace: aditya
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\adityg1\Desktop\aditya\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: redis-server
    spec:
      containers:
      - image: redis:alpine # This will pull public image of redis from docker hub.
        imagePullPolicy: ""
        name: redis-server
        ports:
        - containerPort: 6379 # Expose this port of the container
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
